#!/usr/bin/env python3
"""Turn the hand-drawn track albedo into a yellow-on-transparent floor decal.

The source (`line_track/materials/textures/track_albedo.jpg`) is a black stroke
on white, drawn so the image footprint matches the warehouse floor 1:1:
1006 x 1674 px over 30 x 50 m => 0.02983 m/px (the two axes agree to 0.1%).

The drawn stroke is ~10-12 px (~0.33 m) wide, which is wide for a line-follow
track, so we thin it: Zhang-Suen skeletonize down to the medial axis, then
re-dilate to `--width` metres with an antialiased edge. Thinning-then-dilating
(rather than eroding) keeps the centreline exactly where it was drawn.

Output is RGBA: bright yellow where the stroke is, fully transparent elsewhere,
so the decal shows the warehouse's own floor everywhere else.
"""

import argparse
import pathlib

import numpy as np
from PIL import Image

# Warehouse floor extent, from the Fuel `Warehouse` collision mesh bbox.
FLOOR_X_M = 30.0
FLOOR_Y_M = 50.0

YELLOW = (255, 221, 0)


def skeletonize(mask):
    """Zhang-Suen thinning. `mask` is a bool array; returns a bool skeleton."""
    img = mask.copy()
    # Neighbours P2..P9, clockwise from north, as shifted views of the image.
    def neighbours(a):
        p = np.zeros((8,) + a.shape, dtype=np.uint8)
        p[0, 1:, :] = a[:-1, :]      # P2  N
        p[1, 1:, :-1] = a[:-1, 1:]   # P3  NE
        p[2, :, :-1] = a[:, 1:]      # P4  E
        p[3, :-1, :-1] = a[1:, 1:]   # P5  SE
        p[4, :-1, :] = a[1:, :]      # P6  S
        p[5, :-1, 1:] = a[1:, :-1]   # P7  SW
        p[6, :, 1:] = a[:, :-1]      # P8  W
        p[7, 1:, 1:] = a[:-1, :-1]   # P9  NW
        return p

    while True:
        changed = False
        for step in (0, 1):
            p = neighbours(img.astype(np.uint8))
            b = p.sum(axis=0)                      # number of set neighbours
            # A: 0->1 transitions in the circular sequence P2,P3,...,P9,P2
            seq = np.concatenate([p, p[:1]], axis=0)
            a = ((seq[:-1] == 0) & (seq[1:] == 1)).sum(axis=0)
            if step == 0:
                c1 = p[0] * p[2] * p[4]            # P2*P4*P6
                c2 = p[2] * p[4] * p[6]            # P4*P6*P8
            else:
                c1 = p[0] * p[2] * p[6]            # P2*P4*P8
                c2 = p[0] * p[4] * p[6]            # P2*P6*P8
            kill = img & (b >= 2) & (b <= 6) & (a == 1) & (c1 == 0) & (c2 == 0)
            if kill.any():
                img &= ~kill
                changed = True
        if not changed:
            return img


def distance_to_set(mask, radius):
    """Euclidean distance from every pixel to the nearest True in `mask`.

    Only exact out to `radius`; anything further is left at radius+1. That is
    all the antialiased edge needs, and it keeps this to a fixed number of
    array shifts instead of pulling in scipy (broken against numpy 2.x here).
    """
    r = int(np.ceil(radius)) + 1
    dist = np.full(mask.shape, float(r + 1))
    dist[mask] = 0.0
    h, w = mask.shape
    for dy in range(-r, r + 1):
        for dx in range(-r, r + 1):
            d = float(np.hypot(dy, dx))
            if d == 0.0 or d > r:
                continue
            ys0, ys1 = max(0, dy), min(h, h + dy)
            xs0, xs1 = max(0, dx), min(w, w + dx)
            src = mask[ys0 - dy:ys1 - dy, xs0 - dx:xs1 - dx]
            dst = dist[ys0:ys1, xs0:xs1]
            np.minimum(dst, np.where(src, d, np.inf), out=dst)
    return dist


def write_mesh(path):
    """Write the decal quad, sized from the same constants as the texture.

    The extent lives here and nowhere else. When it was duplicated between this
    script and a hand-written .obj, changing one silently misplaced the whole
    track: the texture still rendered, just at the wrong scale, with nothing to
    warn you.
    """
    hx, hy = FLOOR_X_M / 2.0, FLOOR_Y_M / 2.0
    path.write_text(f"""# Floor decal quad for the warehouse line track.
# GENERATED by gen_track_texture.py - do not edit; change FLOOR_X_M/FLOOR_Y_M
# there and regenerate, so the mesh and the texture scale stay in agreement.
#
# Spans the warehouse floor exactly: x [{-hx:g}, {hx:g}], y [{-hy:g}, {hy:g}], z = 0.
# UVs are written out explicitly rather than relying on <plane>'s implicit
# mapping, so the texture lands on the floor at a known scale and orientation:
# u = 0 at x = {-hx:g} (image column 0), v = 1 at y = {hy:g} (image row 0, top).
mtllib track_plane.mtl
o track_plane
v {-hx:.1f} {-hy:.1f} 0.0
v  {hx:.1f} {-hy:.1f} 0.0
v  {hx:.1f}  {hy:.1f} 0.0
v {-hx:.1f}  {hy:.1f} 0.0
vt 0.0 0.0
vt 1.0 0.0
vt 1.0 1.0
vt 0.0 1.0
vn 0.0 0.0 1.0
usemtl track
f 1/1/1 2/2/1 3/3/1
f 1/1/1 3/3/1 4/4/1
""")


def walk_loop(skel):
    """Order the skeleton pixels along the curve, greedy nearest-neighbour.

    The track is one closed loop, so starting anywhere and always stepping to
    the nearest unvisited pixel walks it exactly once. Returns (col, row) pairs
    in order. A step longer than 3 px means the walk fell off the curve, which
    would mean the drawing is not a single closed loop - so stop there and let
    the caller notice the short result.
    """
    ys, xs = np.nonzero(skel)
    pts = np.stack([xs, ys], axis=1).astype(float)
    used = np.zeros(len(pts), dtype=bool)
    used[0] = True
    order = [0]
    cur = 0
    for _ in range(len(pts) - 1):
        d = np.hypot(pts[:, 0] - pts[cur, 0], pts[:, 1] - pts[cur, 1])
        d[used] = np.inf
        nxt = int(d.argmin())
        if d[nxt] > 3.0:
            break
        used[nxt] = True
        order.append(nxt)
        cur = nxt
    return pts[order]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', required=True, help='hand-drawn albedo (black on white)')
    ap.add_argument('--dst', required=True, help='RGBA decal to write')
    ap.add_argument('--width', type=float, default=0.15,
                    help='painted line width in metres (default 0.15)')
    ap.add_argument('--threshold', type=int, default=128,
                    help='grey level below which a pixel counts as stroke')
    ap.add_argument('--centerline', default=None,
                    help='also write the track centreline as world-frame x,y CSV')
    ap.add_argument('--mesh', default=None,
                    help='also write the decal quad .obj sized from FLOOR_X_M/FLOOR_Y_M')
    args = ap.parse_args()

    grey = np.array(Image.open(args.src).convert('L'))
    h, w = grey.shape
    m_per_px = 0.5 * (FLOOR_X_M / w + FLOOR_Y_M / h)
    mask = grey < args.threshold

    skel = skeletonize(mask)
    radius_px = 0.5 * args.width / m_per_px
    dist = distance_to_set(skel, radius_px + 1.0)
    # 1 px of linear falloff at the edge: crisp centre, no jaggies.
    alpha = np.clip(radius_px + 0.5 - dist, 0.0, 1.0)

    rgba = np.zeros((h, w, 4), dtype=np.uint8)
    rgba[..., 0], rgba[..., 1], rgba[..., 2] = YELLOW
    rgba[..., 3] = (alpha * 255).round().astype(np.uint8)
    Image.fromarray(rgba, 'RGBA').save(args.dst)

    print(f'source        {w} x {h} px, {mask.sum()} stroke px')
    print(f'scale         {m_per_px:.5f} m/px  ({w * m_per_px:.2f} x {h * m_per_px:.2f} m)')
    print(f'line width    {args.width} m  ({2 * radius_px:.2f} px)')
    print(f'skeleton      {skel.sum()} px -> {int((alpha > 0.5).sum())} painted px')
    print(f'wrote         {args.dst}')

    if args.mesh:
        write_mesh(pathlib.Path(args.mesh))
        print(f'wrote         {args.mesh}')

    if args.centerline:
        # Same image -> world mapping the decal quad uses: column 0 is
        # x = -FLOOR_X_M/2, row 0 (top of the image) is y = +FLOOR_Y_M/2.
        loop = walk_loop(skel)
        world = np.stack([-FLOOR_X_M / 2 + loop[:, 0] * (FLOOR_X_M / w),
                          FLOOR_Y_M / 2 - loop[:, 1] * (FLOOR_Y_M / h)], axis=1)
        length = np.hypot(*np.diff(world, axis=0).T).sum()
        gap = float(np.hypot(*(world[0] - world[-1])))
        np.savetxt(args.centerline, world, fmt='%.4f', delimiter=',',
                   header='x,y  (world frame, metres) - track centreline, ordered along the loop')
        print(f'centreline    {len(world)}/{int(skel.sum())} skeleton px walked, '
              f'{length:.1f} m long, closes to {gap * m_per_px:.3f} m')
        print(f'wrote         {args.centerline}')


if __name__ == '__main__':
    main()
