#!/usr/bin/env python3
"""(Re)place the obstacle boxes standing on the painted line in warehouse_line.sdf.

Ten boxes, roughly every 16 m around the 158.6 m loop. Rather than dropping them
at exactly every L/10 - which lands one in a 2.4 m-radius hairpin where a detour
is far harder than the avoidance behaviour is meant to test - each is nudged up
to 6 m along the track to the straightest spot that still keeps:

  * >= MIN_CLEARANCE of measured free space beside the track on at least one
    side, right along the detour - see config/track_clearance.csv. Distance to
    the prop *poses* in the world file was used for this originally and is
    badly wrong: the warehouse building is a single model at the origin, so its
    walls were never considered at all, and boxes landed in spots where the
    robot's swing-out ran straight into a wall;
  * >= 2.2 m to any other branch of the loop, so a detour cannot wander onto a
    different part of the line and confuse the follower;
  * >= 6 m from its neighbours, so they stay roughly periodic.

Box geometry is 0.5 x 0.5 m in plan and 0.7 m tall. The footprint is what forces
the detour (the Husky is 0.67 m wide). The height is set by the sensor, not by
looks: lidar2d sits 0.322 m above base_link and base_link is one wheel radius
(0.1651 m) off the ground, so the scan plane is ~0.487 m up. A 0.5 m cube clears
it by 13 mm and vanishes from the scan as soon as the robot pitches.

Rewrites the obstacle block in place; safe to run repeatedly.

    python3 place_obstacles.py [--world path] [--centerline path] [-n 10]
"""

import argparse
import os
import re

import numpy as np

MARKER = '<!-- OBSTACLE COURSE (generated by place_obstacles.py) -->'
BOX_XY, BOX_Z = 0.5, 0.7

# The detour swings about 0.84 m wide (see the follower's out_heading_deg and
# pass_distance), and the robot is 0.67 m across, so it needs ~1.2 m of free
# space beside the line. 1.6 m leaves a sensible margin on top of that.
MIN_CLEARANCE = 1.6


def curvature_radius(c, i, span=60):
    j, k = max(0, i - span), min(len(c) - 1, i + span)
    a, b, d = c[j], c[i], c[k]
    area = abs((b[0]-a[0])*(d[1]-a[1]) - (d[0]-a[0])*(b[1]-a[1])) / 2
    if area < 1e-6:
        return 999.0
    return min(999.0, np.hypot(*(b-a)) * np.hypot(*(d-b)) * np.hypot(*(d-a)) / (4*area))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--world', default=os.path.join(here, '..', 'worlds', 'warehouse_line.sdf'))
    ap.add_argument('--centerline', default=os.path.join(here, '..', 'config', 'track_centerline.csv'))
    ap.add_argument('--clearance', default=os.path.join(here, '..', 'config', 'track_clearance.csv'))
    ap.add_argument('--min-clearance', type=float, default=MIN_CLEARANCE)
    ap.add_argument('-n', '--count', type=int, default=10)
    args = ap.parse_args()

    c = np.loadtxt(args.centerline, delimiter=',')
    s = np.r_[0, np.cumsum(np.hypot(*np.diff(c, axis=0).T))]
    L = s[-1]
    w = open(args.world).read()
    clear = np.loadtxt(args.clearance, delimiter=',')
    room = np.fmax(clear[:, 0], clear[:, 1])   # the better of the two sides

    props = np.array([[float(p.group(1).split()[0]), float(p.group(1).split()[1])]
                      for m in re.finditer(r'<include>(.*?)</include>', w, re.S)
                      if (p := re.search(r'<pose>([^<]+)</pose>', m.group(1)))])

    def self_dist(i):
        far = (np.abs(s - s[i]) > 8.0) & (np.abs(np.abs(s - s[i]) - L) > 8.0)
        return np.hypot(*(c[far] - c[i]).T).min() if far.any() else 99.0

    chosen = []
    for n in range(args.count):
        target = n * L / args.count
        cand = [i for i in range(len(c)) if abs(s[i] - target) <= 8.0]
        ok = [i for i in cand
              if not np.isnan(room[i]) and room[i] >= args.min_clearance
              and self_dist(i) >= 2.2
              and all(abs(s[i] - s[j]) > 6.0 for j in chosen)]
        if not ok:
            print(f'  ! no spot near {target:.0f} m with {args.min_clearance} m of room; '
                  f'taking the roomiest available')
            ok = [i for i in cand if not np.isnan(room[i])] or cand
            chosen.append(max(ok, key=lambda i: -1e9 if np.isnan(room[i]) else room[i]))
            continue
        # Among the spots with room, prefer the straightest.
        chosen.append(max(ok, key=lambda i: curvature_radius(c, i)))

    blocks = [f'    {MARKER}\n']
    for n, i in enumerate(chosen):
        x, y = c[i]
        j = min(len(c) - 1, i + 20)
        yaw = float(np.arctan2(c[j][1] - y, c[j][0] - x))
        print(f'  obstacle_{n}: ({x:7.2f},{y:7.2f})  arc {s[i]:6.1f} m  '
              f'room {room[i]:.2f} m  R {curvature_radius(c, i):.0f} m')
        blocks.append(f"""    <model name='obstacle_{n}'>
      <static>true</static>
      <pose>{x:.3f} {y:.3f} {BOX_Z/2:.3f} 0 0 {yaw:.4f}</pose>
      <link name='link'>
        <collision name='collision'>
          <geometry><box><size>{BOX_XY} {BOX_XY} {BOX_Z}</size></box></geometry>
        </collision>
        <visual name='visual'>
          <geometry><box><size>{BOX_XY} {BOX_XY} {BOX_Z}</size></box></geometry>
          <material>
            <!-- Red on purpose: the follower thresholds yellow at OpenCV hue
                 18-38 and red sits at hue 0, so a box is never seen as track. -->
            <ambient>0.8 0.1 0.1 1</ambient>
            <diffuse>0.8 0.1 0.1 1</diffuse>
            <specular>0.1 0.1 0.1 1</specular>
          </material>
        </visual>
      </link>
    </model>
""")

    body = ''.join(blocks)
    if MARKER in w:
        # Everything from the marker to the end of the world element is ours,
        # so replace that span wholesale. Searching for the last </model>
        # instead breaks when the previous run wrote no boxes at all.
        start = w.index('    ' + MARKER)
        end = w.index('  </world>', start)
        w = w[:start] + body + w[end:]
    else:
        w = w.replace('  </world>', body + '  </world>', 1)
    open(args.world, 'w').write(w)
    print(f'wrote {args.count} obstacles to {os.path.normpath(args.world)}')


if __name__ == '__main__':
    main()
